- API_DOCUMENTATION.md
API documentation on how to use the RESTful API's in the backend of the project. 
- Documented all API controllers
- Included request and response examples
- Added error code definitions
Let me know if any sections need to be elaborated on more or if formatting needs changes.
Works on #63
> Api documentation

- backend/task-manager/src/main/java/com/example/task_manager/controller/AdminController.java
- backend/task-manager/src/main/java/com/example/task_manager/controller/AuthInfoController.java
- backend/task-manager/src/main/java/com/example/task_manager/controller/IsAssignedController.java
- backend/task-manager/src/main/java/com/example/task_manager/controller/IsMemberOfController.java
- backend/task-manager/src/main/java/com/example/task_manager/controller/TaskController.java
- backend/task-manager/src/main/java/com/example/task_manager/controller/TeamController.java
- backend/task-manager/src/main/java/com/example/task_manager/controller/TeamMemberController.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/AdminControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/AuthInfoControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/IsAssignedControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/IsMemberOfControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/TaskControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/TeamControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/TeamMemberControllerTest.java
Created controller tests to ensure all controllers are/will be working correctly and API requests are successful.
- Works on #40
> API Setup - Controller Tests and Controllers

- backend/task-manager/pom.xml
- backend/task-manager/src/main/java/com/example/task_manager/entity/Admin.java
- backend/task-manager/src/main/java/com/example/task_manager/entity/AuthInfo.java
- backend/task-manager/src/main/java/com/example/task_manager/entity/TeamMember.java
- backend/task-manager/src/main/java/com/example/task_manager/repository/TeamMemberRepository.java
- backend/task-manager/src/main/java/com/example/task_manager/service/AdminService.java
- backend/task-manager/src/main/java/com/example/task_manager/service/AuthInfoService.java
- backend/task-manager/src/main/java/com/example/task_manager/service/TeamMemberService.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/AdminEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/AuthInfoEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/IsAssignedEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/IsMemberOfEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/TaskEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/TeamEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/TeamMemberEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/repository_tests/IsAssignedRepositoryTest.java
- backend/task-manager/src/test/java/com/example/task_manager/repository_tests/IsMemberOfRepositoryTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/AdminServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/AuthInfoServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/IsAssignedServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/IsMemberOfServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/TeamMemberServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/TeamServiceTest.java
Adds passwords to team member constructor, uses the Argon2id hash function with salts for secure passwords.
> Authentication

- frontend/react-app/src/App.js
Created an App.js file to route all html pages. By default, the app will open to the login page. There is also a simple "Page not found" page in case there is no match. Resolve #82
> Router add

- backend/task-manager/src/main/java/com/example/task_manager/config/WebConfig.java
- frontend/react-app/package-lock.json
- frontend/react-app/package.json
- frontend/react-app/src/api/adminApi.js
- frontend/react-app/src/api/authInfo.js
- frontend/react-app/src/api/isAssignedApi.js
- frontend/react-app/src/api/isMemberOfApi.js
- frontend/react-app/src/api/taskApi.js
- frontend/react-app/src/api/teamApi.js
- frontend/react-app/src/api/teamMemberApi.js
- frontend/react-app/src/setupTests.js
- frontend/react-app/src/tests/api-tests/adminApiTest.test.js
- frontend/react-app/src/tests/api-tests/isAssignedApi.test.js
- frontend/react-app/src/tests/api-tests/isMemberOfApiTest.test.js
- frontend/react-app/src/tests/api-tests/taskApiTest.test.js
- frontend/react-app/src/tests/api-tests/teamApiTest.test.js
- frontend/react-app/src/tests/api-tests/teamMemberApiTest.test.js
Implemented frontend API services. Added imports and necessary dependencies to setupTests, package.json, and package-lock.json
> frontend API services

- API_DOCUMENTATION.md
- backend/task-manager/src/main/java/com/example/task_manager/DTO/AuthInfoDTO.java
- backend/task-manager/src/main/java/com/example/task_manager/controller/AuthController.java
- backend/task-manager/src/main/java/com/example/task_manager/controller/AuthInfoController.java
- backend/task-manager/src/main/java/com/example/task_manager/service/AuthInfoService.java
- backend/task-manager/src/main/java/com/example/task_manager/service/TeamMemberService.java
- backend/task-manager/src/test/java/com/example/task_manager/DTO_tests/AuthInfoDTOTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/AuthInfoControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/AuthInfoServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/TeamMemberServiceTest.java
- frontend/react-app/src/api/authInfo.js
- frontend/react-app/src/tests/api-tests/authInfoApiTest.test.js
Added backend and frontend methods and classes to ensure a user can login, as well as to check whether a user is an admin or not. All test implemented and API documentation updated to reflect these AuthInfo changes.
Resolves #92
> Get role backend

- frontend/react-app/src/components/TeamMember.jsx
- frontend/react-app/src/css/TeamTasks.css
- frontend/react-app/src/pages/TeamTasks.jsx
edited team tasks page to account for both admin and team member users 
uses mock data
> Team tasks admin page

- DOCKER_DOCUMENTATION.md
- backend/task-manager/Dockerfile
- docker-compose.yml
- frontend/react-app/Dockerfile
- frontend/react-app/nginx.conf
Implemented docker image and container files. Docker can run both frontend and backend.
nginx is a web server that serves static files, allowing for docker to run the frontend React project. It takes the API requests from the frontend and serves them to the backend, and vice versa.
Resolves #76
> Docker image m2

- backend/task-manager/src/main/java/com/example/task_manager/DTO/IsAssignedDTO.java
- backend/task-manager/src/main/java/com/example/task_manager/entity/IsAssigned.java
- backend/task-manager/src/main/java/com/example/task_manager/service/AuthInfoService.java
- backend/task-manager/src/main/java/com/example/task_manager/service/TeamMemberService.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/AdminControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/AuthInfoControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/IsAssignedControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/IsMemberOfControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/TaskControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/TeamControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/TeamMemberControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/AdminEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/AuthInfoEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/IsAssignedEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/IsMemberOfEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/TaskEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/TeamEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/TeamMemberEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/repository_tests/IsMemberOfRepositoryTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/AdminServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/AuthInfoServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/IsAssignedServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/IsMemberOfServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/TeamMemberServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/TeamServiceTest.java
Changed some tests in the backend to ensure they are correct. Removed all setUp methods to isolate each test and avoid all persistence errors.
Resolves #124
> Backend testing changes

- API_DOCUMENTATION.md
- backend/task-manager/src/main/java/com/example/task_manager/controller/AdminController.java
- backend/task-manager/src/main/java/com/example/task_manager/controller/TeamMemberController.java
- backend/task-manager/src/main/java/com/example/task_manager/repository/TeamMemberRepository.java
- backend/task-manager/src/main/java/com/example/task_manager/service/AdminService.java
- backend/task-manager/src/main/java/com/example/task_manager/service/TeamMemberService.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/AdminControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/TeamMemberControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/TeamMemberServiceTest.java
- frontend/react-app/src/api/adminApi.js
- frontend/react-app/src/api/teamMemberApi.js
- frontend/react-app/src/tests/api-tests/adminApiTest.test.js
- frontend/react-app/src/tests/api-tests/teamMemberApiTest.test.js
Added new API endpoints with implemented tests and frontend API methods for frontend requirements. Updated API documentation.
Resolves #100 
Resolves #101
> Added new API endpoints 

- API_DOCUMENTATION.md
Fixed the API documentation formatting, it was missing dashes on a few API endpoints.
> API Formatting

- API_DOCUMENTATION.md
- backend/task-manager/src/main/java/com/example/task_manager/DTO/TaskDTO.java
- backend/task-manager/src/main/java/com/example/task_manager/DTO/TaskRequestDTO.java
- backend/task-manager/src/main/java/com/example/task_manager/entity/Task.java
- backend/task-manager/src/main/java/com/example/task_manager/enums/TaskPriority.java
- backend/task-manager/src/main/java/com/example/task_manager/service/TeamMemberService.java
- backend/task-manager/src/test/java/com/example/task_manager/DTO_tests/TaskDTOTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/TeamMemberControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/IsAssignedEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/NotificationEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/TaskEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/TeamEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/entity_tests/TeamMemberEntityTest.java
- backend/task-manager/src/test/java/com/example/task_manager/repository_tests/IsAssignedRepositoryTest.java
- backend/task-manager/src/test/java/com/example/task_manager/repository_tests/NotificationRepositoryTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/AdminServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/IsAssignedServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/NotificationServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/TeamMemberServiceTest.java
- frontend/react-app/src/api/teamMemberApi.js
- frontend/react-app/src/components/CreateTaskForm.jsx
- frontend/react-app/src/components/EditTaskForm.jsx
- frontend/react-app/src/tests/api-tests/teamMemberApiTest.test.js
Implemented priority field to Task. Created enum file to hold the possible types of priorities. Adjusted all backend methods to account for new priority field. Changed tests to account for new field. Updated frontend to use the new priority field, and updated API documentation.
ALL tests are running and passing.
Resolves #158
> Priority field for Task

- API_DOCUMENTATION.md
- backend/task-manager/src/main/java/com/example/task_manager/DTO/TeamMemberWithTeamLeadDTO.java
- backend/task-manager/src/main/java/com/example/task_manager/controller/AdminController.java
- backend/task-manager/src/main/java/com/example/task_manager/repository/TeamRepository.java
- backend/task-manager/src/main/java/com/example/task_manager/service/AdminService.java
- backend/task-manager/src/test/java/com/example/task_manager/DTO_tests/TeamMemberWithTeamLeadDTOTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/AdminControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/repository_tests/TeamRepositoryTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/AdminServiceTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/TeamServiceTest.java
Changed the getAllTeamMembers method in AdminService to return whether a team member is a team lead, and if so a list of all team ID's that they lead and a list of all team names that they lead. Updated API documentation to match the changes, no changes necessary to the frontend API endpoint or equivalent test.
Resolves #174
> Added teamLead in getAllTeamMembers in AdminService

- API_DOCUMENTATION.md
- backend/task-manager/src/main/java/com/example/task_manager/DTO/ResetPasswordRequestDTO.java
- backend/task-manager/src/main/java/com/example/task_manager/controller/TeamMemberController.java
- backend/task-manager/src/main/java/com/example/task_manager/service/AuthInfoService.java
- backend/task-manager/src/main/java/com/example/task_manager/service/TeamMemberService.java
- backend/task-manager/src/test/java/com/example/task_manager/DTO_tests/ResetPasswordRequestDTOTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/TeamMemberControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/TeamMemberServiceTest.java
- frontend/react-app/package-lock.json
- frontend/react-app/src/api/teamMemberApi.js
- frontend/react-app/src/tests/api-tests/teamMemberApiTest.test.js
Implemented new API endpoint, reset password.
The reset password method does NOT require the old password to change the password, this endpoint should only be available to admins.
All backend and frontend has been implemented, and the API documentation ahs been updated to mirror the new endpoint available.
Resolves #172
> Change password api

- API_DOCUMENTATION.md
- backend/task-manager/src/main/java/com/example/task_manager/DTO/ChangeRoleRequestDTO.java
- backend/task-manager/src/main/java/com/example/task_manager/controller/AdminController.java
- backend/task-manager/src/main/java/com/example/task_manager/service/AdminService.java
- backend/task-manager/src/test/java/com/example/task_manager/DTO_tests/ChangeRoleRequestDTOTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/AdminControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/AdminServiceTest.java
- frontend/react-app/package-lock.json
- frontend/react-app/src/api/adminApi.js
- frontend/react-app/src/tests/api-tests/adminApiTest.test.js
Changed the promoteToAdmin method to allow for any user to be promoted to admin or demoted to team member.
Ensured all new tests are passing, they are.
Updated frontend and API documentation to reflect the changes made in backend and frontend.
Removed/changed all mentions of promoteToAdmin. 
When the member is promoted or demoted they will be provided a new ID.
Resolves #173
> Add demote api

- API_DOCUMENTATION.md
- backend/task-manager/src/main/java/com/example/task_manager/controller/TeamController.java
- backend/task-manager/src/main/java/com/example/task_manager/repository/TaskRepository.java
- backend/task-manager/src/main/java/com/example/task_manager/service/TeamService.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/TeamControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/repository_tests/TaskRepositoryTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/TeamServiceTest.java
- frontend/react-app/src/api/teamApi.js
- frontend/react-app/src/tests/api-tests/teamApiTest.test.js
Implemented the getTeamTasks API endpoint so when provided a team ID it will return all tasks associated to the team through the team members. So any team member assigned to the team will have their tasks returned.
All tests are passing.
Resolves #176
> Get teamtasks api

- API_DOCUMENTATION.md
- backend/task-manager/src/main/java/com/example/task_manager/controller/TeamMemberController.java
- backend/task-manager/src/main/java/com/example/task_manager/service/TeamMemberService.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/TeamMemberControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/TeamMemberServiceTest.java
- frontend/react-app/src/api/teamMemberApi.js
- frontend/react-app/src/tests/api-tests/teamMemberApiTest.test.js
Created a mass assignToTask API endpoint, so multiple users can be assigned to a task at the same time.
Resolves #177
> Mass add to task api

- frontend/react-app/package-lock.json
- frontend/react-app/src/components/TeamMember.jsx
- frontend/react-app/src/pages/Home.js
- frontend/react-app/src/pages/TeamTasks.jsx
- to do table and completed table connected to api in team tasks
-connected to team buttons in home page
-prints no tasks if no tasks found
-list of team members in team connected to API
Resolves #135
> Team tasks to api

- frontend/react-app/package-lock.json
- frontend/react-app/src/components/TeamMember.jsx
- frontend/react-app/src/pages/Home.js
- frontend/react-app/src/pages/TeamTasks.jsx
connected table in home page to api
> Home table to api

- backend/task-manager/src/main/java/com/example/task_manager/service/AdminService.java
Manually creating new IsAssigned and IsMemberOf relationships, so making a copy because the old ones get deleted when the member gets deleted.
> ChangeRole api not working, fix

- backend/task-manager/src/main/java/com/example/task_manager/controller/AdminController.java
- backend/task-manager/src/main/java/com/example/task_manager/service/AdminService.java
Fixing issue where admin would not delet. Added debug API methods, although they are commented out in case of future need.
> Admin Not deletign fix

- frontend/react-app/src/pages/MyTasks.jsx
- frontend/react-app/src/pages/TeamTasks.jsx
-added completed task table thats connected to the api in myTasks page
-fixed completed task table in team tasks
Resolves #210
> My tasks complete tasks

- backend/task-manager/src/main/java/com/example/task_manager/entity/Admin.java
- backend/task-manager/src/main/java/com/example/task_manager/entity/AuthInfo.java
- backend/task-manager/src/main/java/com/example/task_manager/entity/IsAssigned.java
- backend/task-manager/src/main/java/com/example/task_manager/entity/IsMemberOf.java
- backend/task-manager/src/main/java/com/example/task_manager/entity/TeamMember.java
- backend/task-manager/src/main/java/com/example/task_manager/service/AdminService.java
Changed the changeRole method to work, it had hibernate constraint issues caused by foriegn relations.
The promoted/demoted member gets a new ID, and their notifications get deleted, so be careful when promoting and demoting a member.
> Fixing change role

- API_DOCUMENTATION.md
- backend/task-manager/src/main/java/com/example/task_manager/DTO/TeamMemberInTeamDTO.java
- backend/task-manager/src/main/java/com/example/task_manager/controller/TeamController.java
- backend/task-manager/src/main/java/com/example/task_manager/service/TeamMemberService.java
- backend/task-manager/src/main/java/com/example/task_manager/service/TeamService.java
- backend/task-manager/src/test/java/com/example/task_manager/DTO_tests/TeamMemberInTeamDTOTest.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/TeamControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/TeamServiceTest.java
Updated the API documentation to show that the role gets returned when getTeamMembers method is called for a specific team. 
Changed the getTeamMembers method inside TeamService to return a boolean of whether they are a teamlead  (true) or not (false). Created a new DTO that contains isTeamLead field, and added new ConvertToDTO method in TeamService.
Updated backend tests to use TeamMemberInTeamDTO instead of TeamMemberDTO.
Created DTO tests for the new DTO class TeamMemberInTeamDTO.
Updated API documentation to reflect the new field.
Resolves #193
> Roles get team members api

- backend/task-manager/src/main/java/com/example/task_manager/service/AdminService.java
Making changeRole recreate the memberships and assignments the original account had.
> changeRole fix 

- backend/task-manager/src/main/java/com/example/task_manager/service/AdminService.java
Ensuring the memberships and tasks are being saved to database.
> Change Role Saving tasks/memberships fix

- frontend/react-app/src/api/isAssignedApi.js
- frontend/react-app/src/api/teamMemberApi.js
- frontend/react-app/src/components/CreateAccountForm.jsx
- frontend/react-app/src/components/CreateTaskForm.jsx
- frontend/react-app/src/components/EditTaskForm.jsx
- frontend/react-app/src/components/TaskList.jsx
- frontend/react-app/src/css/CreateTaskForm.css
- frontend/react-app/src/css/ViewTask.css
- frontend/react-app/src/pages/EditTask.jsx
- frontend/react-app/src/pages/Home.js
- frontend/react-app/src/pages/MyTasks.jsx
- frontend/react-app/src/pages/TeamTasks.jsx
- frontend/react-app/src/pages/ViewTask.jsx
- frontend/react-app/src/tests/EditTaskForm.test.js
- frontend/react-app/src/tests/UserInfo.test.js
- frontend/react-app/src/tests/UserTable.test.js
You can now update view edit all the tasks also fixes create task
Resolves #219
> View and edit task connect api

- frontend/react-app/src/pages/MyTasks.jsx
- frontend/react-app/src/pages/TeamTasks.jsx
made a common method for headerandAccessors in myTasks page and teamTasks page
resolves #235
> fixed duplicate headerandAccessor method in my tasks and team tasks pages

- backend/task-manager/src/main/java/com/example/task_manager/service/AdminService.java
Refactoring changeRole method to use helper methods, which removes duplicate code in promote and demote methods.
> Refactoring changeRole method 

- frontend/react-app/src/css/MyTasks.css
- frontend/react-app/src/pages/Notifications.jsx
Restructured table sections into reusable components, which avoids duplicate code and multiple calls to filter() for both read and unread notifications.
resolves #248
> Refactored notifications

- frontend/react-app/src/FakeData/fakeTaskData.json
- frontend/react-app/src/components/CreateTaskForm.jsx
> Fixing typos in frontend.

- backend/task-manager/src/main/java/com/example/task_manager/service/AdminService.java
Fixing bug where a user is no longer the team lead when their role is changed.
All test are passing still, and this change was manually tested as well to ensure it functions correctly.
Resolves #224
> Fix to make member remain as team lead when their role is changed.

- API_DOCUMENTATION.md
- backend/task-manager/src/main/java/com/example/task_manager/controller/IsMemberOfController.java
- backend/task-manager/src/main/java/com/example/task_manager/controller/TeamMemberController.java
- backend/task-manager/src/main/java/com/example/task_manager/service/IsMemberOfService.java
- backend/task-manager/src/test/java/com/example/task_manager/TaskManagerApplicationTests.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/IsMemberOfControllerTest.java
- backend/task-manager/src/test/java/com/example/task_manager/service_tests/IsMemberOfServiceTest.java
- frontend/react-app/src/api/isMemberOfApi.js
- frontend/react-app/src/tests/api-tests/isMemberOfApiTest.test.js
Adding mass assign to team API method. All changed/new tests are passing. API documentation is updated.
Resolves #274
> Mass assign team

- frontend/react-app/package-lock.json
- frontend/react-app/package.json
- frontend/react-app/src/components/Header.jsx
- frontend/react-app/src/css/Header.css
Added logout function to header, so user can logout from header and from the profile page
> Logout header

- frontend/react-app/src/components/CreateTaskForm.jsx
- frontend/react-app/src/css/CreateTask.css
- frontend/react-app/src/css/CreateTaskForm.css
- frontend/react-app/src/css/home.css
- frontend/react-app/src/index.css
- frontend/react-app/src/pages/CreateTask.jsx
Cleaned up create task CSS. Centered everything and made it a nicer size, and more consistent with the colour scheme. Changed borders as well (also for focus). Added placeholder text to form. Changed description to textarea. resolves #281
> Create task CSS updates

- frontend/react-app/src/css/home.css
- frontend/react-app/src/pages/Home.jsx
Changed home page to match colours a bit more, added boxes and a line. Added a link to the word Tasks, which takes the user to their tasks.
Resolves #286
> Changed UI, added link to Tasks when hovering.

- frontend/react-app/src/components/Header.jsx
- frontend/react-app/src/login.css
Changed login colour and added notification icon on header.
Resolves #289
> Changed login colour and added notification icon on header.

- backend/task-manager/src/main/java/com/example/task_manager/controller/NotificationController.java
- backend/task-manager/src/test/java/com/example/task_manager/controller_tests/NotificationControllerTest.java
- frontend/react-app/src/api/notificationApi.js
- frontend/react-app/src/components/Notification.jsx
- frontend/react-app/src/pages/Notifications.jsx
- frontend/react-app/src/tests/Notifications.test.js
- frontend/react-app/src/tests/api-tests/notificationApiTest.test.js
I connected the API to the notifications page and added a header. 
Resolves #293
> Api to notifications

- frontend/react-app/src/css/TaskList.css
Changing text filter color from red to slate grey
> Changing text filter color from red to slate grey

- frontend/react-app/src/components/UserInfo.jsx
- frontend/react-app/src/css/Profile.css
- frontend/react-app/src/pages/Profile.jsx
Changed profile page image to react icon and added space between header and user info
> Slight profile page changes

- frontend/react-app/src/css/CreateTaskForm.css
- frontend/react-app/src/css/MyTasks.css
- frontend/react-app/src/pages/MyTasks.jsx
Fixed task page UI to match the rest of the website. 
Resolves #297
> Making task page ui prettier, and match the rest of the ui.

- frontend/react-app/src/components/TaskList.jsx
- frontend/react-app/src/components/UserTable.jsx
- frontend/react-app/src/css/TaskList.css
Fixed all spacing on all tables
Resolves #316
> Fix spacing on task list

- frontend/react-app/src/css/ViewTask.css
- frontend/react-app/src/index.css
- frontend/react-app/src/pages/ViewTask.jsx
Fixed formatting and changed colours. Resolves #308
> Fixed css for view task page

- frontend/react-app/src/components/LockUnlockTask.jsx
- frontend/react-app/src/css/MyTasks.css
- frontend/react-app/src/pages/MyTasks.jsx
Changing the lock icon, and making it green for unlocked, red for locked
Resolves #306
> Changing lock icon

- frontend/react-app/src/components/EditTaskForm.jsx
- frontend/react-app/src/css/CreateTaskForm.css
- frontend/react-app/src/css/EditTask.css
Fixed the input field on the edit task page. Added a background and changed colours a bit. Resolves #309
> Polished edit task page

- frontend/react-app/src/css/Profile.css
- frontend/react-app/src/pages/Profile.jsx
Changing profile page to match the rest of the website
Resolves #314
> Changing profile page to match the rest of the website

- frontend/react-app/src/components/CreateTeamForm.jsx
Changed the spacing between the buttons and the inputs and the text
Resolves #318
> Spacing the button, inputs, and text on create team form.

- frontend/react-app/src/css/EditUserDetails.css
- frontend/react-app/src/pages/EditUserDetails.jsx
Fixed formatting and changed some colours. Resolves #317
> Fixed css for edit user details

- frontend/react-app/src/components/LockUnlockTask.jsx
- frontend/react-app/src/pages/MyTasks.jsx
- frontend/react-app/src/pages/TeamTasks.jsx
> Got rid of reload on lock

- frontend/react-app/src/css/ChangePassword.css
- frontend/react-app/src/pages/ChangePassword.jsx
Changed the colours, adjusted layout. Resolves #329
> Updated change password css

- frontend/react-app/src/css/home.css
Added margin to the bottom of the home page
> Fixing home page bottom margin

- frontend/react-app/src/pages/MyTasks.jsx
- frontend/react-app/src/pages/TeamTasks.jsx
different coloured text for priority column in task tables
resolves #305 resolves #307
> priority changes color in task tables

- backend/task-manager/src/main/java/com/example/task_manager/service/TeamMemberService.java
> Making a notf be created when assigned to a task.
